models/Image.php
<?php
/**
 * Класс таблицы image.
 * Created by PhpStorm.
 * User: x0st
 * Date: 13.08.16
 * Time: 02:39
 */

namespace app\models;


use yii\db\ActiveRecord;

/**
 * Class Image
 * @package app\models
 * @property mixed id
 * @property mixed name
 * @property mixed branches
 */
class Image extends ActiveRecord
{
    /**
     * @return string
     */
    public static function tableName()
    {
        return 'image';
    }

    /**
     * После удаления образа удаляем все его ветки.
     */
    public function afterDelete()
    {
        ImageBranch::deleteAll(['image_id' => $this->id]);
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }

    /**
     * Фк-ция для with().
     * @return \yii\db\ActiveQuery
     */
    public function getBranches()
    {
        return $this->hasMany(ImageBranch::className(), ['image_id' => 'id']);
    }
}

models/ImageForm.php
<?php
/**
 * Создание, обновление образа, веток образа.
 * Created by PhpStorm.
 * User: x0st
 * Date: 13.08.16
 * Time: 14:58
 */

namespace app\models;

use avega\EditableTable;

class ImageForm extends Image
{
    /**
     * Ветки из формы.
     * @var array
     */
    public $branches;

    /**
     * В случае обновления образа, после сохранения, если были созданы новые ветки, здесь будет массив id новых веток
     * чтобы обновить id в editable table на стороне js.
     * @var array
     */
    public $branchesIds;

    /**
     * Правила валидации.
     * @return array
     */
    public function rules()
    {
        return [
            [['name', 'branches'], 'required'],
            ['branches', 'validateBranchesArray']
        ];
    }

    /**
     * Проверяет массив веток.
     * @param $attribute
     */
    public function validateBranchesArray($attribute)
    {
        $rules = [
            [['name'], 'required'],
            ['build', 'in', 'range' => ['', '1'], 'strict' => true]
        ];

        if (!EditableTable::validate($rules, $this->branches)) {
            $this->addError($attribute, 'Branches have incorrect format.');
        }
    }

    /**
     * Обновляет, удаляет, создает ветки для образа.
     */
    private function setBranches()
    {
        $table = new EditableTable(ImageBranch::className());
        $table->setValues($this->branches);
        $this->branchesIds = $table->save(['image_id' => $this->id]);
    }

    /**
     * После сохранения обновляем ветки.
     * @param bool $insert
     * @param array $changedAttributes
     */
    public function afterSave($insert, $changedAttributes)
    {
        $this->setBranches();
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}

controllers/ImagesController.php
<?php
/**
 * Страница со всеми образами, удаление, обновление, создание.
 * Created by PhpStorm.
 * User: x0st
 * Date: 13.08.16
 * Time: 02:36
 */

namespace app\controllers;


use app\models\ApplicationContainer;
use app\models\Image;
use app\models\ImageBranch;
use app\models\ImageForm;
use app\models\ImageList;
use avega\F;
use yii\web\BadRequestHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class ImagesController extends CommonController
{
    private $response = ['status' => 0];

    /**
     * Страница со списком всех образов.
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Удаляет образ (ajax).
     */
    public function actionDelete($id)
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

        $image = Image::findOne($id);

        if ($image !== null) {
            if (count(ApplicationContainer::findAll(['image_id' => $image->id])) > 0) {
                $this->response['messages'] = 'You cannot delete the image because this one is used by a container.';
            } elseif ($image->delete()) {
                $this->response = ['messages' => '«' . $image->name . '» image has been deleted.', 'status' => 1];
            } else {
                throw new BadRequestHttpException();
            }
        } else {
            throw new NotFoundHttpException();
        }

        return $this->response;
    }

    /**
     * Возвращает список образов с пагинацией (ajax).
     */
    public function actionGetList()
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

        return ImageList::getList();
    }

    /**
     * Страница создания нового образа.
     */
    public function actionNew()
    {
        return $this->render('new');
    }

    /**
     * Страница редактирования образа.
     */
    public function actionEdit($id)
    {
        $image = Image::findOne($id);

        if ($image !== null) {
            return $this->render('edit', [
                'image' => $image,
                'branches' => ImageBranch::findAll(['image_id' => $id])
            ]);
        } else {
            throw new NotFoundHttpException();
        }
    }

    /**
     * Создает или обновляет образ и его ветки (ajax).
     */
    public function actionSave($id = null)
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

        if ($id === null) {
            $model = new ImageForm();
        } else {
            $model = ImageForm::findOne($id);

            if ($model === null) {
                throw new NotFoundHttpException();
            }
        }

        // транзакция потому что еще обновляются ветки образа
        $transaction = $model::getDb()->beginTransaction();

        try {

            if ($model->load(\Yii::$app->request->post(), 'form') && $model->save()) {
                $this->response['status'] = 1;

                if ($id === null) {
                    $this->response['messages'] = '«' . $model->name . '» image has been created.';
                } else {
                    $this->response['messages'] = 'Image has been updated.';
                    $this->response['updates'] = $model->branchesIds;
                }

                $transaction->commit();

            } elseif ($model->hasErrors()) {
                $this->response['messages'] = $model->errors;
            } else {
                throw new BadRequestHttpException();
            }
        } catch (\Exception $err) {
            $transaction->rollBack();

            throw new BadRequestHttpException();
        }

        return $this->response;
    }
}

views/images/edit.php
<?php
/**
 * Created by PhpStorm.
 * User: x0st
 * Date: 13.08.16
 * Time: 17:02
 * @var $image \app\models\Image
 * @var $branches \app\models\ImageBranch[]
 */
?>
<div class="content-header">
    <div class="row">
        <div class="col-md-6 pull-left">
            <h3>Image: <?= $image->name ?></h3>
        </div>
    </div>
</div>
<div data-alert-form></div>
<div class="content">
    <div class="box box-solid">
        <div class="box-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="name">Name</label>
                         <input type="text" id="name" class="form-control" value="<?= $image->name ?>">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-warning btn-lg btn-update">Update</button>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group"></div>
                    <table id="branches" class="table-bordered table-striped table">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Build</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {

        var table = new EditableTable('branches', {
            'tableSelector': '#branches',
            'structure': [
                {'name': 'name', 'type': 'string'},
                {'name': 'build', 'type': 'checkbox'}
            ]
        });

        // в таблицу добавляем ветки образа
        <?php if ($branches !== null): ?>
        <?php foreach ($branches as $branch): ?>
            table.addRow({
                _id: <?= $branch->id ?>,
                name: '<?= $branch->name ?>',
                build: '<?= $branch->build ?>'
            }, false);
        <?php endforeach ?>
        <?php endif ?>

        table.displayRows();

        // перед отправкой формы собираем ветки
        Form.prototype.beforeSubmit = function () {
            return {'branches': table.compileRows()};
        };

        // после отправки формы очищаем таблицу от удаленных строк, подставляем новые id, если строки были созданы,
        // отображаем заново
        Form.prototype.afterUpdate = function (response) {

            if (response.status == 1) {
                table.updateIds(response.updates);
            }

            table.cleanDeletedRows();
            table.displayRows();
            this.afterSubmit(response, 'update');
        };

        new Form('image', {
            'action': 'update',
            'url': '<?= \yii\helpers\Url::to(['/images/save/' . $image->id]) ?>',
            'fields': ['name']
        });
    });
</script>

views/images/index.php
<?php
/**
 * Created by PhpStorm.
 * User: x0st
 * Date: 13.08.16
 * Time: 02:50
 */
?>
<div class="content-header">
    <div class="row">
        <div class="col-md-6 pull-left">
            <h3>Images</h3>
        </div>
        <div class="col-md-6 pull-right">
            <a href="<?= \yii\helpers\Url::to(['/images/new']) ?>" class="btn btn-warning pull-right">New image</a>
        </div>
    </div>
</div>
<div data-alert-list-table></div>
<div class="content">
    <div class="box box-solid">
        <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                <?= \app\widgets\ListTable::widget([
                        'id' => 'images',
                        'columns' => [
                            'id' => ['Id'],
                            'name' => ['Name'],
                            'actions' => true,
                        ],
                        'pagination' => true
                    ]) ?>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        (new ListTable('images', {
            structure: ['id', 'name'],
            tableSelector: '#images',
            url: '<?= \yii\helpers\Url::to(['/images/get-list']) ?>',
            actions: {
                'edit': {ajax: false},
                'delete': {ajax: true}
            }
        })).load();
    });
</script>

views/images/new.php
<?php
/**
 * Created by PhpStorm.
 * User: x0st
 * Date: 13.08.16
 * Time: 03:44
 */
?>
<div class="content-header">
    <div class="row">
        <div class="col-md-6 pull-left">
            <h3>New image</h3>
        </div>
    </div>
</div>
<div data-alert-form></div>
<div class="content">
    <div class="box box-solid">
        <div class="box-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" id="name" class="form-control">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-warning btn-lg btn-create">Create</button>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group"></div>
                    <table id="branches" class="table-bordered table-striped table">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Build</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {

        var table = new EditableTable('branches', {
            'tableSelector': '#branches',
            'structure': [
                {'name': 'name', 'type': 'string'},
                {'name': 'build', 'type': 'checkbox'}
            ]
        });

        table.displayRows();

        // перед отправкой формы собираем ветки
        Form.prototype.beforeSubmit = function () {
            return {'branches': table.compileRows()};
        };

        // после отправки формы очищаем таблицу от удаленных строк, отображаем заново
        Form.prototype.afterCreate = function (response) {
            table.cleanDeletedRows();
            table.displayRows();
            this.afterSubmit(response, 'create');
        };

        new Form('image', {
            'action': 'create',
            'url': '<?= \yii\helpers\Url::to(['/images/save']) ?>',
            'fields': ['name']
        });
    });
</script>