models/User.php
<?php
/**
 * Класс таблицы user.
 */
namespace app\models;

use Yii;
use yii\db\ActiveRecord;

/**
 * Class User
 * @package app\models
 * @property string password_hash
 * @property mixed auth_key
 * @property mixed id
 * @property mixed username
 * @property mixed name
 */
class User extends ActiveRecord implements \yii\web\IdentityInterface
{
    /**
     * @return string
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return self::findOne($id);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return self::findOne(['auth_key' => $token]);
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return self::findOne(['username' => $username]);
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->auth_key === $authKey;
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * @param $password
     */
    public function setPassword($password)
    {
        if (isset($this->password)) unset($this->password);

        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }
}

models/UserForm.php
<?php
/**
 * Модель для создания, редактирования юзера.
 * Created by PhpStorm.
 * User: x0st
 * Date: 13.08.16
 * Time: 00:24
 */

namespace app\models;


class UserForm extends User
{
    /**
     * Пароль из формы.
     * @var string
     */
    public $password;

    const SCENARIO_CREATE = 'create';
    const SCENARIO_UPDATE = 'update';

    /**
     * Какие колонки в каком сценарии учавствуют.
     * @return array
     */
    public function scenarios()
    {
        return [
            self::SCENARIO_CREATE => ['name', 'username', 'password'],
            self::SCENARIO_UPDATE => ['name', 'username', 'password']
        ];
    }

    /**
     * Правила валидации.
     * @return array
     */
    public function rules()
    {
        return [
            [['name', 'username'], 'required'],
            ['password', 'string', 'length' => [6, 36]],
            ['username', 'string', 'length' => [4, 36]],
            ['password', 'required', 'on' => self::SCENARIO_CREATE],
            ['username', 'unique'],
            [['name', 'username'], 'trim']
        ];
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        // если юзер обновляет акк и ввел новый пароль или юзер создает новый аккк
        if (($this->scenario === self::SCENARIO_UPDATE && !empty($this->password)) || ($this->scenario === self::SCENARIO_CREATE)) {
            $this->setPassword($this->password);
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * Названия полей.
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'username' => 'Username',
            'password' => 'Password',
            'name' => 'Name'
        ];
    }
}

controllers/UsersController.php
<?php
/**
 * Страница просмотра юзеров, удаление юзера, создание, обновление.
 * Created by PhpStorm.
 * User: x0st
 * Date: 12.08.16
 * Time: 21:36
 */

namespace app\controllers;


use app\models\User;
use app\models\UserForm;
use app\models\UserList;
use avega\F;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class UsersController extends CommonController
{
    private $response = ['status' => 0];

    /**
     * Страница просмотра юзеров.
     */
    public function actionIndex()
    {

        return $this->render('index');
    }

    /**
     * Возвращает список юзеров с пагинацией (ajax).
     */
    public function actionGetList()
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

        return UserList::getList();
    }

    /**
     * Удаляет юзера (ajax).
     */
    public function actionDelete($id)
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

        if ($id !== \Yii::$app->user->getId()) {
            $user = User::findOne($id);

            if ($user !== null) {
                if ($user->delete()) {
                    $this->response = ['status' => 1, 'messages' => '«' . $user->name . '» user has been deleted.'];
                } else {
                    $this->response['messages'] = 'Deleting error';
                }
            } else {
                throw new NotFoundHttpException();
            }
        } else {
            throw new BadRequestHttpException();
        }

        return $this->response;
    }

    /**
     * Обновляет или создает нового юзера (ajax).
     */
    public function actionSave($id = null)
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

        if ($id == null) {
            $model = new UserForm(['scenario' => UserForm::SCENARIO_CREATE]);
        } else {
            $model = UserForm::findOne($id);

            if ($model === null) {
                throw new NotFoundHttpException();
            } else {
                $model->setScenario(UserForm::SCENARIO_UPDATE);
            }
        }

        if ($model->load(\Yii::$app->request->post(), 'form') && $model->save()) {
            $this->response['status'] = 1;

            if ($model->scenario === $model::SCENARIO_UPDATE) {
                $this->response['messages'] = 'User has been updated.';
            } else {
                $this->response['messages'] = '«' . $model->name . '» user has been created.';
            }
        } elseif ($model->hasErrors()) {
            $this->response['messages'] = $model->errors;
        } else {
            throw new BadRequestHttpException();
        }

        return $this->response;
    }

    /**
     * Страница создания нового юзера.
     */
    public function actionNew()
    {
        return $this->render('new');
    }

    /**
     * Страница редактирования юзера.
     */
    public function actionEdit($id)
    {
        $user = User::findOne($id);

        if ($user !== null) {
            return $this->render('edit', ['user' => $user]);
        } else {
            throw new NotFoundHttpException();
        }
    }
}

views/users/edit.php
<?php
/**
 * Created by PhpStorm.
 * User: x0st
 * Date: 13.08.16
 * Time: 03:30
 * @var $user \app\models\User
 */
?>
<div class="content-header">
    <div class="row">
        <div class="col-md-6 pull-left">
            <h3>User: <?= $user->name ?></h3>
        </div>
    </div>
</div>
<div data-alert-form></div>
<div class="content">
    <div class="box box-solid">
        <div class="box-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" id="name" class="form-control" value="<?= $user->name ?>">
                    </div>
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input type="text" id="username" class="form-control" value="<?= $user->username ?>">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="text" id="password" class="form-control" value="">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-warning btn-lg btn-update">Update</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        // после сохранения обновляем имя юзера в хедере страницы
        Form.prototype.afterUpdate = function (response, data) {
            $('.content-header').find('h3').text('User: ' + data['name']);
            this.afterSubmit(response, 'update');
        };

        new Form('user', {
            'action': 'update',
            'url': '<?= \yii\helpers\Url::to(['/users/save/' . $user->id]) ?>',
            'fields': ['name', 'username', 'password']
        });
    });
</script>

views/users/index.php
<?php
/**
 * Created by PhpStorm.
 * User: x0st
 * Date: 12.08.16
 * Time: 23:09
 */
?>
<div class="content-header">
    <div class="row">
        <div class="col-md-6 pull-left">
            <h3>Users</h3>
        </div>
        <div class="col-md-6 pull-right">
            <a href="<?= \yii\helpers\Url::to(['/users/new']) ?>" class="btn btn-warning pull-right">New user</a>
        </div>
    </div>
</div>
<div data-alert-list-table></div>
<div class="content">
    <div class="box-solid box">
        <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <?= \app\widgets\ListTable::widget([
                        'id' => 'users',
                        'columns' => [
                            'id' => ['Id'],
                            'name' => ['Name'],
                            'username' => ['Username'],
                            'actions' => true,
                        ],
                        'pagination' => true
                    ]) ?>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        (new ListTable('users', {
            structure: ['id', 'name', 'username'],
            tableSelector: '#users',
            url: '<?= \yii\helpers\Url::to(['/users/get-list']) ?>',
            actions: {
                'edit': {ajax: false},
                'delete': {ajax: true}
            }
        })).load();
    });
</script>

views/users/new.php
<?php
/**
 * Created by PhpStorm.
 * User: x0st
 * Date: 13.08.16
 * Time: 00:10
 */
?>
<div class="content-header">
    <div class="row">
        <div class="col-md-6 pull-left">
            <h3>New user</h3>
        </div>
    </div>
</div>
<div data-alert-form></div>
<div class="content">
    <div class="box box-solid">
        <div class="box-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" id="name" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input type="text" id="username" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="text" id="password" class="form-control">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-warning btn-lg btn-create">Create</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        new Form('user', {
            'action': 'create',
            'url': '<?= \yii\helpers\Url::to(['/users/save']) ?>',
            'fields': ['name', 'username', 'password']
        });
    });
</script>